# Generated by Django 3.1.7 on 2021-03-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_name1'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth_user',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='auth_user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
