# Generated by Django 3.1.7 on 2021-03-27 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210326_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth_user',
            name='about',
        ),
        migrations.RemoveField(
            model_name='auth_user',
            name='profile_pic',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=1000)),
                ('Profile_pic', models.ImageField(blank=True, upload_to='p_img')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
