# Generated by Django 3.1.7 on 2021-04-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auth_user_doctor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth_user',
            name='activation_code',
            field=models.CharField(default='nocode', max_length=11),
        ),
        migrations.AddField(
            model_name='auth_user',
            name='activation_code_provided',
            field=models.CharField(default='null', max_length=11),
        ),
    ]
