# Generated by Django 3.1.7 on 2021-04-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210418_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_user',
            name='activation_code_provided',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
