# Generated by Django 3.1.7 on 2021-04-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210418_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth_user',
            name='activated',
        ),
        migrations.RemoveField(
            model_name='auth_user',
            name='activation_code',
        ),
        migrations.RemoveField(
            model_name='auth_user',
            name='activation_code_provided',
        ),
    ]
