# Generated by Django 3.1.7 on 2021-04-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210418_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth_user',
            name='about',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='auth_user',
            name='activation_code_provided',
            field=models.CharField(blank=True, default='none', max_length=11),
        ),
    ]
