# Generated by Django 3.1.7 on 2021-06-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_resetpw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_certification',
            name='user',
        ),
        migrations.DeleteModel(
            name='resetpw',
        ),
        migrations.DeleteModel(
            name='user_certification',
        ),
    ]
