# Generated by Django 3.1.7 on 2021-06-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210602_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auth_user',
            old_name='is_doctor',
            new_name='is_normal',
        ),
        migrations.RemoveField(
            model_name='auth_user',
            name='about',
        ),
        migrations.RemoveField(
            model_name='auth_user',
            name='activated',
        ),
        migrations.RemoveField(
            model_name='auth_user',
            name='activation_code',
        ),
        migrations.RemoveField(
            model_name='auth_user',
            name='activation_code_provided',
        ),
        migrations.RemoveField(
            model_name='auth_user',
            name='doctor_type',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
