# Generated by Django 3.1.7 on 2021-06-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20210609_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.TextField(default='Unknown', max_length=50),
        ),
    ]
